/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.Subject.SubjectController;
import Models.SemesterModel;
import Models.SubjectModel;
import Models.YearModel;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class SubjectRegistration extends javax.swing.JFrame {

    ArrayList<SubjectModel> arrayList;

    SubjectController subjectController;

    DefaultTableModel defaultTableModel;

    ArrayList<SemesterModel> semesterModels;

    ArrayList<YearModel> yearModels;

    public SubjectRegistration() {
        initComponents();

        arrayList = new ArrayList();
        semesterModels = new ArrayList();
        yearModels = new ArrayList();

        defaultTableModel = (DefaultTableModel) tablemodel.getModel();

        subjectController = new SubjectController();

        tablemodel.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tablemodel.getTableHeader().setOpaque(false);
        tablemodel.getTableHeader().setBackground(new Color(32, 136, 203));
        tablemodel.getTableHeader().setForeground(new Color(255, 255, 255));
        tablemodel.setRowHeight(25);

        loadSemesters();
        loadYears();
        loadData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nooftutorialhours = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        numberoflecturehours = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        noofevaluationhours = new javax.swing.JTextField();
        subjectname = new javax.swing.JTextField();
        subjectcode = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        numberoflabhours = new javax.swing.JTextField();
        semestercombo = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        yearcombo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablemodel = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(245, 245, 245));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ABC INSTITUE TIME TABLE MANAGEMENT SYSTEM");

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ABC Institute, New Kandy Rd, Malabe 10115");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/abc.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 60));

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 535));

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Register a New Subject");

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel5.setText("  Offered Year");

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel7.setText(" Subject Name");

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel8.setText(" Subject Code");

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel9.setText(" Number of Lecture Hours");

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel10.setText(" Number of Tutorial Hours");

        nooftutorialhours.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        nooftutorialhours.setForeground(new java.awt.Color(51, 51, 51));
        nooftutorialhours.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nooftutorialhoursKeyTyped(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(118, 255, 3));
        jButton1.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/Success.png"))); // NOI18N
        jButton1.setText("SAVE");
        jButton1.setToolTipText("");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/hover_btn.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/reset_btn.png"))); // NOI18N
        jButton3.setText("DELETE");
        jButton3.setToolTipText("");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/hover_btn.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        numberoflecturehours.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        numberoflecturehours.setForeground(new java.awt.Color(51, 51, 51));
        numberoflecturehours.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                numberoflecturehoursKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numberoflecturehoursKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel11.setText(" Number of Evaluation Hours");

        noofevaluationhours.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        noofevaluationhours.setForeground(new java.awt.Color(51, 51, 51));
        noofevaluationhours.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                noofevaluationhoursKeyTyped(evt);
            }
        });

        subjectname.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        subjectname.setForeground(new java.awt.Color(51, 51, 51));

        subjectcode.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        subjectcode.setForeground(new java.awt.Color(51, 51, 51));

        jLabel15.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel15.setText("Number of Lab Hours");

        numberoflabhours.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        numberoflabhours.setForeground(new java.awt.Color(51, 51, 51));
        numberoflabhours.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numberoflabhoursKeyTyped(evt);
            }
        });

        semestercombo.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        semestercombo.setForeground(new java.awt.Color(51, 51, 51));
        semestercombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Y1.S1", "Y1.S2" }));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/reset_btn.png"))); // NOI18N
        jButton4.setText("UPDATE");
        jButton4.setToolTipText("");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusPainted(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/hover_btn.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        yearcombo.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        yearcombo.setForeground(new java.awt.Color(51, 51, 51));
        yearcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Y1.S1", "Y1.S2" }));

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel6.setText("Semester");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(yearcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(semestercombo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(subjectname)
                    .addComponent(subjectcode)
                    .addComponent(numberoflecturehours)
                    .addComponent(nooftutorialhours)
                    .addComponent(numberoflabhours)
                    .addComponent(noofevaluationhours)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(53, 53, 53)
                                .addComponent(jLabel6))
                            .addComponent(jLabel7)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel15)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yearcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(semestercombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subjectname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subjectcode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numberoflecturehours, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nooftutorialhours, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numberoflabhours, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noofevaluationhours, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 250, 535));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setViewportBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jScrollPane1.setFocusable(false);

        tablemodel.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        tablemodel.setForeground(new java.awt.Color(51, 51, 51));
        tablemodel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "2", "OOC ", "45", "8", null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Year", "Semester", "Subject", "Code", "N L Hrs", "N T Hrs", "N Lb Hrs", "N E Hrs"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablemodel.setGridColor(new java.awt.Color(255, 255, 255));
        tablemodel.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tablemodel.setRowHeight(25);
        tablemodel.setShowVerticalLines(false);
        tablemodel.getTableHeader().setReorderingAllowed(false);
        tablemodel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablemodelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablemodel);
        if (tablemodel.getColumnModel().getColumnCount() > 0) {
            tablemodel.getColumnModel().getColumn(0).setResizable(false);
            tablemodel.getColumnModel().getColumn(1).setResizable(false);
            tablemodel.getColumnModel().getColumn(2).setResizable(false);
            tablemodel.getColumnModel().getColumn(3).setResizable(false);
            tablemodel.getColumnModel().getColumn(4).setResizable(false);
            tablemodel.getColumnModel().getColumn(5).setResizable(false);
            tablemodel.getColumnModel().getColumn(6).setResizable(false);
            tablemodel.getColumnModel().getColumn(7).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 530, 410));

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Register a New Lecturer");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel13.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Registered Subject List");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 64, 530, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (tablemodel.getRowCount() > 0 && tablemodel.getSelectedRow() > -1) {
            int x = subjectController.delete(arrayList.get(tablemodel.getSelectedRow()).getSubject_id());

            if (x == 1) {
                clearAll();
            } else {
                JOptionPane.showMessageDialog(null, "Something Error");
            }
            loadData();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (semestercombo.getItemCount() > 0) {
            if (!subjectname.getText().isEmpty() && !subjectcode.getText().isEmpty() && !numberoflecturehours.getText().isEmpty() && !nooftutorialhours.getText().isEmpty() && !numberoflabhours.getText().isEmpty() && !noofevaluationhours.getText().isEmpty()) {
                int x = subjectController.store(new SubjectModel(subjectname.getText(), subjectcode.getText(), numberoflecturehours.getText(), nooftutorialhours.getText(), numberoflabhours.getText(), noofevaluationhours.getText(), 1, new SemesterModel(semesterModels.get(semestercombo.getSelectedIndex()).getSemester_id(), null), yearModels.get(yearcombo.getSelectedIndex()).getId()));

                if (x == 1) {
                    clearAll();
                } else {
                    JOptionPane.showMessageDialog(null, "Something Error");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please Fill All The Fields");
            }
        } else {
            JOptionPane.showMessageDialog(null, "No Semesters Found");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (tablemodel.getRowCount() > 0 && tablemodel.getSelectedRow() > -1) {
            if (semestercombo.getItemCount() > 0) {
                if (!subjectname.getText().isEmpty() && !subjectcode.getText().isEmpty() && !numberoflecturehours.getText().isEmpty() && !nooftutorialhours.getText().isEmpty() && !numberoflabhours.getText().isEmpty() && !noofevaluationhours.getText().isEmpty()) {
                    int x = subjectController.update(new SubjectModel(arrayList.get(tablemodel.getSelectedRow()).getSubject_id(), subjectname.getText(), subjectcode.getText(), numberoflecturehours.getText(), nooftutorialhours.getText(), numberoflabhours.getText(), noofevaluationhours.getText(), 1, new SemesterModel(semesterModels.get(semestercombo.getSelectedIndex()).getSemester_id(), null), yearModels.get(yearcombo.getSelectedIndex()).getId()));

                    if (x == 1) {
                        JOptionPane.showMessageDialog(null, "Updated");
                        clearAll();
                    } else {
                        JOptionPane.showMessageDialog(null, "Something Error");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Please Fill All The Fields");
                }
            } else {
                JOptionPane.showMessageDialog(null, "No Semesters Found");
            }
        } else {
            JOptionPane.showMessageDialog(null, "First Select Data Row");
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void tablemodelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablemodelMouseClicked

        SubjectModel subjectModel = arrayList.get(tablemodel.getSelectedRow());

        subjectname.setText(subjectModel.getSubject_name());
        subjectcode.setText(subjectModel.getSubject_code());
        numberoflecturehours.setText(subjectModel.getNo_of_lec_hours());
        nooftutorialhours.setText(subjectModel.getNo_of_tu_hours());
        numberoflabhours.setText(subjectModel.getNo_of_lab_hours());
        noofevaluationhours.setText(subjectModel.getNo_of_eva_hours());

        int x1 = 0;

        for (YearModel yearModel : yearModels) {
            if (yearModel.getId() == subjectModel.getYear()) {
                yearcombo.setSelectedIndex(x1);
                break;
            }
            x1++;
        }

        int x2 = 0;

        for (SemesterModel yearModel : semesterModels) {
            if (yearModel.getSemester_id() == subjectModel.getSemesterModel().getSemester_id()) {
                semestercombo.setSelectedIndex(x2);
                break;
            }
            x2++;
        }


    }//GEN-LAST:event_tablemodelMouseClicked

    private void numberoflecturehoursKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numberoflecturehoursKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_numberoflecturehoursKeyTyped

    private void numberoflecturehoursKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numberoflecturehoursKeyPressed

    }//GEN-LAST:event_numberoflecturehoursKeyPressed

    private void nooftutorialhoursKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nooftutorialhoursKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_nooftutorialhoursKeyTyped

    private void numberoflabhoursKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numberoflabhoursKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_numberoflabhoursKeyTyped

    private void noofevaluationhoursKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noofevaluationhoursKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_noofevaluationhoursKeyTyped

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        this.setVisible(false);
        Dashboard d = new Dashboard();
        d.setVisible(true);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void clearAll() {
        subjectname.setText("");
        subjectcode.setText("");
        numberoflecturehours.setText("");
        nooftutorialhours.setText("");
        numberoflabhours.setText("");
        noofevaluationhours.setText("");
        loadSemesters();
        loadData();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubjectRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubjectRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubjectRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubjectRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubjectRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField noofevaluationhours;
    private javax.swing.JTextField nooftutorialhours;
    private javax.swing.JTextField numberoflabhours;
    private javax.swing.JTextField numberoflecturehours;
    private javax.swing.JComboBox<String> semestercombo;
    private javax.swing.JTextField subjectcode;
    private javax.swing.JTextField subjectname;
    private javax.swing.JTable tablemodel;
    private javax.swing.JComboBox<String> yearcombo;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        defaultTableModel.setRowCount(0);
        arrayList.clear();
        arrayList = subjectController.getAll();
        arrayList.forEach((data) -> {
            Vector vectorData = new Vector();

            for (YearModel yearObj : yearModels) {
                if (yearObj.getId() == data.getYear()) {
                    vectorData.add(yearObj.getYear());
                    break;
                }
            }

            vectorData.add(data.getSemesterModel().getSemester());
            vectorData.add(data.getSubject_name());
            vectorData.add(data.getSubject_code());
            vectorData.add(data.getNo_of_lec_hours());
            vectorData.add(data.getNo_of_tu_hours());
            vectorData.add(data.getNo_of_lab_hours());
            vectorData.add(data.getNo_of_eva_hours());

            defaultTableModel.addRow(vectorData);
        });
    }

    private void loadSemesters() {
        semesterModels.clear();
        semestercombo.removeAllItems();
        semesterModels = subjectController.getSemesters();
        semesterModels.forEach((data) -> semestercombo.addItem(data.getSemester()));
    }

    private void loadYears() {
        yearModels.clear();
        yearcombo.removeAllItems();
        yearModels.add(new YearModel(1, "1st Year"));
        yearModels.add(new YearModel(2, "2nd Year"));
        yearModels.add(new YearModel(3, "3rd Year"));
        yearModels.add(new YearModel(4, "4th Year"));
        yearModels.forEach((data) -> yearcombo.addItem(data.getYear()));
    }
}
